version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    container_name: gobankpgcontainer
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gobankdatabase
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
